### ISSUE TITLE
Having issues with latest commit :/

### ISSUE THREAD

**Issue by eduardo-escoto** [tristansizik/Hello-World#1]
I have a problem with "lol u suk tho".
It should obviously be changed to:

# *YOU ARE AMAZING AND MAGICAL*

**Comment by tristansizik** [comment]
Wow. I can't believe I overlooked that typo. 
### I APPRECIATE YOU MY KING
@ goodvibesonly

**Comment by eduardo-escoto** [comment]
# 🥰
